PROJECT_BASE_SITE = $(call github,aesd-nettle,project_base)
PROJECT_BASE_SITE_METHOD = git
PROJECT_BASE_LICENSE = GPLv2
PROJECT_BASE_LICENSE_FILES = COPYING
PROJECT_BASE_DEPENDENCIES = host-pkgconf pkgconf
PROJECT_BASE_INSTALL_STAGING = YES

